<?php
/**
 * single.php — Blog Post Single Template
 *
 * @package JJWeddingZ
 */

get_header();

the_post();

$thumb        = get_the_post_thumbnail_url( null, 'jjwz-blog-hero' );
$cats         = get_the_category();
$cat_name     = $cats ? $cats[0]->name : '';
$cat_link     = $cats ? get_category_link( $cats[0]->term_id ) : '';
$word_count   = str_word_count( get_the_content() );
$read_time    = max( 1, ceil( $word_count / 200 ) );
$focus_kw     = function_exists( 'get_field' ) ? get_field( 'blog_focus_keyword' ) : '';
$wa_link      = 'https://wa.me/' . preg_replace( '/[^0-9]/', '', jjwz_get_option( 'jjwz_whatsapp_number', '919876543210' ) );
$tags         = get_the_tags();
?>

<article id="post-<?php the_ID(); ?>" <?php post_class( 'jjwz-single-post' ); ?>>

    <!-- ═══════════════════════════════
         POST HERO
         ═══════════════════════════════ -->
    <header class="post-hero" aria-label="Article header">
        <div class="post-hero__bg" aria-hidden="true">
            <?php if ( $thumb ) : ?>
                <img src="<?php echo esc_url( $thumb ); ?>" alt="" class="post-hero__img" fetchpriority="high" decoding="sync">
            <?php else : ?>
                <img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/placeholder-blog.png' ); ?>" alt="" class="post-hero__img" fetchpriority="high" decoding="sync">
            <?php endif; ?>
            <div class="post-hero__overlay"></div>
        </div>
        <div class="container post-hero__content">
            <?php jjwz_breadcrumb(); ?>
            <?php if ( $cat_name ) : ?>
            <a href="<?php echo esc_url( $cat_link ); ?>" class="eyebrow post-hero__cat">
                <?php echo esc_html( $cat_name ); ?>
            </a>
            <?php endif; ?>
            <h1 class="post-hero__title"><?php the_title(); ?></h1>
            <div class="post-hero__meta">
                <div class="post-meta__author">
                    <?php echo get_avatar( get_the_author_meta( 'ID' ), 32, '', '', [ 'class' => 'post-meta__avatar' ] ); ?>
                    <span>By <?php the_author(); ?></span>
                </div>
                <time datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>" class="post-meta__date">
                    <?php echo get_the_date( 'F j, Y' ); ?>
                </time>
                <span class="post-meta__read-time">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                    <?php echo $read_time; ?> min read
                </span>
            </div>
        </div>
    </header>

    <!-- ═══════════════════════════════
         ARTICLE BODY
         ═══════════════════════════════ -->
    <div class="post-layout container">
        <div class="post-layout__main">

            <!-- Table of Contents (auto-generated by JS) -->
            <div class="post-toc" id="post-toc" aria-label="Table of contents" hidden>
                <h2 class="post-toc__title">In This Article</h2>
                <nav id="post-toc-nav"></nav>
            </div>

            <!-- Content -->
            <div class="post-content" id="post-content">
                <?php the_content(); ?>
                <?php
                wp_link_pages( [
                    'before' => '<div class="post-pagination">Pages: ',
                    'after'  => '</div>',
                ] );
                ?>
            </div>

            <!-- Tags -->
            <?php if ( $tags ) : ?>
            <div class="post-tags">
                <span class="post-tags__label">Topics:</span>
                <?php foreach ( $tags as $tag ) : ?>
                <a href="<?php echo esc_url( get_tag_link( $tag->term_id ) ); ?>" class="post-tag">
                    <?php echo esc_html( $tag->name ); ?>
                </a>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>

            <!-- Author Box -->
            <div class="post-author-box">
                <?php echo get_avatar( get_the_author_meta( 'ID' ), 72, '', '', [ 'class' => 'post-author-box__avatar' ] ); ?>
                <div class="post-author-box__info">
                    <span class="post-author-box__label">Written by</span>
                    <strong class="post-author-box__name"><?php the_author(); ?></strong>
                    <p class="post-author-box__bio"><?php echo esc_html( get_the_author_meta( 'description' ) ?: 'JJ WeddingZ Photography — Luxury wedding, maternity, and newborn photography across Delhi NCR and Amritsar, India.' ); ?></p>
                </div>
            </div>

            <!-- Share -->
            <div class="post-share">
                <span class="post-share__label">Share This Article</span>
                <div class="post-share__btns">
                    <?php
                    $post_url   = rawurlencode( get_permalink() );
                    $post_title = rawurlencode( get_the_title() );
                    ?>
                    <a href="https://wa.me/?text=<?php echo $post_title . '%20' . $post_url; ?>" target="_blank" rel="noopener" class="share-btn share-btn--wa" aria-label="Share on WhatsApp">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12.003 2a9.987 9.987 0 00-8.59 15.04L2 22l5.115-1.34A9.993 9.993 0 0012.003 22c5.514 0 10-4.486 10-10s-4.486-10-9.997-10zm0 18.212a8.184 8.184 0 01-4.17-1.146l-.3-.178-3.09.81.824-3.01-.195-.31A8.198 8.198 0 013.802 12c0-4.517 3.676-8.195 8.2-8.195 4.517 0 8.196 3.678 8.196 8.195 0 4.52-3.68 8.212-8.196 8.212z"/></svg>
                        WhatsApp
                    </a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $post_url; ?>" target="_blank" rel="noopener" class="share-btn share-btn--fb" aria-label="Share on Facebook">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>
                        Facebook
                    </a>
                    <a href="https://twitter.com/intent/tweet?text=<?php echo $post_title; ?>&url=<?php echo $post_url; ?>" target="_blank" rel="noopener" class="share-btn share-btn--tw" aria-label="Share on Twitter/X">
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.747l7.73-8.835L1.254 2.25H8.08l4.259 5.63zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
                        Share
                    </a>
                </div>
            </div>

            <!-- Related Posts -->
            <?php
            $related = new WP_Query( [
                'post_type'           => 'post',
                'posts_per_page'      => 3,
                'post_status'         => 'publish',
                'post__not_in'        => [ get_the_ID() ],
                'orderby'             => 'rand',
                'category__in'        => $cats ? array_column( $cats, 'term_id' ) : [],
                'ignore_sticky_posts' => true,
            ] );
            if ( $related->have_posts() ) :
            ?>
            <div class="related-posts">
                <h3 class="related-posts__heading">You May Also Like</h3>
                <div class="related-posts__grid">
                    <?php while ( $related->have_posts() ) : $related->the_post();
                        $rt      = get_the_post_thumbnail_url( null, 'jjwz-blog-card' );
                        $rc      = get_the_category();
                        $rc_name = $rc ? $rc[0]->name : '';
                    ?>
                    <a href="<?php the_permalink(); ?>" class="related-post-card">
                        <div class="related-post-card__media">
                            <?php if ( $rt ) : ?>
                                <img src="<?php echo esc_url( $rt ); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy">
                            <?php else : ?>
                                <img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/placeholder-blog.png' ); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy" style="width:100%; height:100%; object-fit:cover;">
                            <?php endif; ?>
                        </div>
                        <div class="related-post-card__body">
                            <?php if ( $rc_name ) : ?><span class="related-post-card__cat"><?php echo esc_html( $rc_name ); ?></span><?php endif; ?>
                            <h4 class="related-post-card__title"><?php the_title(); ?></h4>
                        </div>
                    </a>
                    <?php endwhile; wp_reset_postdata(); ?>
                </div>
            </div>
            <?php endif; ?>

            <!-- Comments -->
            <?php if ( comments_open() || get_comments_number() ) : ?>
            <div class="post-comments" id="comments">
                <?php comments_template(); ?>
            </div>
            <?php endif; ?>

        </div><!-- /.post-layout__main -->

        <!-- Sidebar -->
        <aside class="post-layout__sidebar" aria-label="Blog sidebar">

            <!-- Sticky CTA -->
            <div class="sidebar-cta">
                <div class="sidebar-cta__icon">📸</div>
                <h3 class="sidebar-cta__heading">Planning a Wedding in Delhi or Amritsar?</h3>
                <p class="sidebar-cta__desc">Book a consultation with our team. Limited dates available for <?php echo gmdate('Y'); ?>.</p>
                <a href="<?php echo esc_url( $wa_link ); ?>"
                   class="btn btn--primary sidebar-cta__btn" target="_blank" rel="noopener noreferrer"
                   id="sidebar-wa-cta">
                    Inquire Now
                </a>
            </div>

            <!-- Blog Categories -->
            <div class="sidebar-widget">
                <h3 class="sidebar-widget__title">Browse by Category</h3>
                <ul class="sidebar-cats">
                    <?php
                    $side_cats = get_categories( [ 'hide_empty' => true ] );
                    foreach ( $side_cats as $sc ) :
                    ?>
                    <li class="sidebar-cats__item <?php echo ( $cats && $sc->term_id === $cats[0]->term_id ) ? 'is-active' : ''; ?>">
                        <a href="<?php echo esc_url( get_category_link( $sc->term_id ) ); ?>">
                            <?php echo esc_html( $sc->name ); ?>
                            <span class="sidebar-cats__count"><?php echo $sc->count; ?></span>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <!-- Recent Posts -->
            <div class="sidebar-widget">
                <h3 class="sidebar-widget__title">Recent Articles</h3>
                <?php
                $recent = get_posts( [ 'posts_per_page' => 5, 'post_status' => 'publish', 'post__not_in' => [ get_the_ID() ] ] );
                foreach ( $recent as $rp ) :
                    $rp_thumb = get_the_post_thumbnail_url( $rp->ID, 'jjwz-thumb' );
                ?>
                <a href="<?php echo esc_url( get_permalink( $rp->ID ) ); ?>" class="sidebar-recent-item">
                    <?php if ( $rp_thumb ) : ?>
                        <img src="<?php echo esc_url( $rp_thumb ); ?>" alt="" loading="lazy" class="sidebar-recent-item__img">
                    <?php endif; ?>
                    <span class="sidebar-recent-item__title"><?php echo esc_html( $rp->post_title ); ?></span>
                </a>
                <?php endforeach; ?>
            </div>

            <?php if ( is_active_sidebar( 'blog-sidebar' ) ) : ?>
                <?php dynamic_sidebar( 'blog-sidebar' ); ?>
            <?php endif; ?>

        </aside><!-- /.post-layout__sidebar -->

    </div><!-- /.post-layout -->

</article>

<?php get_footer(); ?>
